### ISSUE TITLE
reactivity issue after errors.clear('field')

### ISSUE THREAD

**Issue by burlresearch** [sahibalejandro/form-object#2]
On new Laravel 5.5 project I'm working I'm experiencing an issue that I think is a Vue reactivity issue. Calling:
```
this.form.errors.clear('email');
```
certainly calls `delete` on the field, but even in my Vue Inspector in Chrome devtools I have to hit `refresh` to see the Vue instance update - and the error class on the wrapping div is not getting removed. This seems pretty straightforward to me, and that it should work. Is there something wrong here that others have experienced this too?
Here's the simple template code:
```
<div class="form-group" :class="{ 'has-error': form.errors.has('email') }">
    <label for="email" class="col-md-3 control-label">email</label>
    <div class="col-md-9">
        <input type="text" class="form-control" id="email" name="email" v-model="vattr.email">
        <div class="help-block" v-for="(error, key) in form.errors.getAll('email')" :key="key" v-text="error"></div>
    </div>
</div>
```

**Comment by sahibalejandro** [comment]
Thanks for the feedbak.
